### ISSUE TITLE
Error when parse text in staging with entity labels

### ISSUE THREAD

**Issue by douglasppaz** [Ilhasoft/bothub-nlp#62]
```
bothub-nlp_1     | Traceback (most recent call last):
bothub-nlp_1     |   File "/usr/local/lib/python3.6/site-packages/tornado/web.py", line 1548, in _stack_context_handle_exception
bothub-nlp_1     |     raise_exc_info((type, value, traceback))
bothub-nlp_1     |   File "<string>", line 4, in raise_exc_info
bothub-nlp_1     |   File "/usr/local/lib/python3.6/site-packages/tornado/stack_context.py", line 339, in wrapped
bothub-nlp_1     |     ret = fn(*args, **kwargs)
bothub-nlp_1     |   File "/usr/local/lib/python3.6/site-packages/tornado/web.py", line 1767, in future_complete
bothub-nlp_1     |     f.result()
bothub-nlp_1     |   File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 307, in wrapper
bothub-nlp_1     |     result = func(*args, **kwargs)
bothub-nlp_1     |   File "/usr/local/lib/python3.6/types.py", line 248, in wrapped
bothub-nlp_1     |     coro = func(*args, **kwargs)
bothub-nlp_1     |   File "/home/app/bothub_nlp/server/utils.py", line 34, in check
bothub-nlp_1     |     return f(handler, *args, **kwargs)
bothub-nlp_1     |   File "/home/app/bothub_nlp/server/handlers/parse.py", line 41, in post
bothub-nlp_1     |     self._parse(text, language, rasa_format)
bothub-nlp_1     |   File "/home/app/bothub_nlp/server/handlers/parse.py", line 59, in _parse
bothub-nlp_1     |     answer = parse_text(update, text, rasa_format=rasa_format)
bothub-nlp_1     |   File "/home/app/bothub_nlp/core/parse.py", line 80, in parse_text
bothub-nlp_1     |     current_label_items = list(entities.get(label_value))
bothub-nlp_1     | TypeError: 'NoneType' object is not iterable
bothub-nlp_1     | 2018-08-28 23:25:22,660 - bothub_nlp.server - ERROR - Traceback (most recent call last):
bothub-nlp_1     |    File "/usr/local/lib/python3.6/site-packages/tornado/web.py", line 1548, in _stack_context_handle_exception
bothub-nlp_1     |     raise_exc_info((type, value, traceback))
bothub-nlp_1     |    File "<string>", line 4, in raise_exc_info
bothub-nlp_1     |    File "/usr/local/lib/python3.6/site-packages/tornado/stack_context.py", line 339, in wrapped
bothub-nlp_1     |     ret = fn(*args, **kwargs)
bothub-nlp_1     |    File "/usr/local/lib/python3.6/site-packages/tornado/web.py", line 1767, in future_complete
bothub-nlp_1     |     f.result()
bothub-nlp_1     |    File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 307, in wrapper
bothub-nlp_1     |     result = func(*args, **kwargs)
bothub-nlp_1     |    File "/usr/local/lib/python3.6/types.py", line 248, in wrapped
bothub-nlp_1     |     coro = func(*args, **kwargs)
bothub-nlp_1     |    File "/home/app/bothub_nlp/server/utils.py", line 34, in check
bothub-nlp_1     |     return f(handler, *args, **kwargs)
bothub-nlp_1     |    File "/home/app/bothub_nlp/server/handlers/parse.py", line 41, in post
bothub-nlp_1     |     self._parse(text, language, rasa_format)
bothub-nlp_1     |    File "/home/app/bothub_nlp/server/handlers/parse.py", line 59, in _parse
bothub-nlp_1     |     answer = parse_text(update, text, rasa_format=rasa_format)
bothub-nlp_1     |    File "/home/app/bothub_nlp/core/parse.py", line 80, in parse_text
bothub-nlp_1     |     current_label_items = list(entities.get(label_value))
bothub-nlp_1     |  TypeError: 'NoneType' object is not iterable
```

**Comment by douglasppaz** [comment]
Same issue reported here... (but in production)
https://github.com/Ilhasoft/bothub/issues/24

**Comment by douglasppaz** [comment]
Confirmed bug in production:

![image](https://user-images.githubusercontent.com/8301135/45317770-55999480-b511-11e8-9a0c-99d3d8fe2554.png)
